server:
    error:
        include-message: always
spring:
    application:
        teste
    datasource:
        driverClassName: org.postgresql.Driver
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/advices_db
        username: postgres
        password: postgrespw
        properties:
            hibernate:
                dialect: io.r2dbc.postgresql.PostgresqlDialect

#logging:
#    level:
#        root: debug

# actuator
management:
    endpoint:
        health:
            show-details: always
        web:
            exposure:
                include:*
info:
    app:
        name: @project.name@
        description: @project.description@
        version: @project.version@
        encoding: @project.build.sourceEncoding@
        java:
            version: @java.version@


