server:
    error:
        include-message: always
spring:
    application:
        teste
    datasource:
        driverClassName: org.postgresql.Driver
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: username
        password: 1234
        properties:
            hibernate:
                dialect: io.r2dbc.postgresql.PostgresqlDialect
logging:
    level:
        org.springframework.data.r2dbc: Debug

# actuator
management:
    endpoint:
        health:
            show-details: always
        web:
            exposure:
                include:*
info:
    app:
        name: @project.name@
        description: @project.description@
        version: @project.version@
        encoding: @project.build.sourceEncoding@
        java:
            version: @java.version@


